### ISSUE TITLE
Unable to define the visibillity of get/set inside a Property

### ISSUE THREAD

**Issue by hilario-cunha** [vaclav/mpscs#12]
Hi,

I haven't been able to set the visibility of the get/set part of a property.

Having the following property
```
public string P1
{
  get;
  set;
}
```
I'm being unable to transform that in
```
public string P1
{
  get;
  protected set;
}
```
I tried also to fix the possible problem directly in the CsBaseLanguage but it was failing when i tried to do the regeneration of the language.

There is a way to do this? 

If not, i will try again to solve the problem in the CsBaseLanguage.

**Comment by wirthma** [comment]
Hello,

thanks for reporting this. That was a bug. I fixed it.

Martin
