### ISSUE TITLE
Suggestion: Using of a substitute menu to modify the auto complete of GenericMemberReference

### ISSUE THREAD

**Issue by hilario-cunha** [vaclav/mpscs#13]
Hi,

I have a suggestion.
When you are using classes that use generics, it is difficult to know which is the correct option to choose in the auto complete. 
As such I suggest a substitute menu to customize the auto complete.

I have already an example on branch https://github.com/hilario-cunha/mpscs/tree/GenericMemberReference_Autocomplete (it's easier to show than explaining)
You can see the example in the GenericClass model.

In that version, on the autocomplete appears the name of the class plus the types used in the definition.
What you think of the suggestion?

**Comment by hilario-cunha** [comment]
Now is creating the GenericMemberReference with the correct number of innerTypes when you choose the reference.

**Comment by wirthma** [comment]
Hello Hilário,

great job, thank you. Merged.

Martin
