### ISSUE TITLE
Scope support

### ISSUE THREAD

**Issue by micfort** [vaclav/mpscs#17]
Hi, 

Thank you for this work. But when I tried it, I noticed there is no scope support in the language.
Is that something that is worked on or planned? Or am I missing something?

**Comment by wirthma** [comment]
Hello @micfort,

unfortunately, the scoping aspect is currently not supported (see the future work section in the document [here](https://github.com/vaclav/mpscs/blob/master/doc/MPSCS_%20Documentation.pdf)) and it is neither being developed as far as I know. This project got created as an academic work, later handed over to the open-source community, which might be interested in further extending. As the original team doesn't find the capacity for that, I'm afraid it's a matter of a volunteer who will implement that.

Have a great day,
@wirthma

**Comment by micfort** [comment]
Hi,

I was already afraid that you were going to say that. Thank you for answering, maybe in the future I will try such endeavor. 
But for now I have to deal with it as is.
