### ISSUE TITLE
Tutorial does not work

### ISSUE THREAD

**Issue by Plasmadog** [vaclav/mpscs#7]
I have followed the tutorial_program exactly, but when previewing the generated text, it does not produce a cs file. Instead I get a tab titled TextGen, containing the following:
`Model processed:r:eeedaff5-feee-4227-9a4c-f40fbda9be3c(CsSampleSln.MyModel)
Context node:r:eeedaff5-feee-4227-9a4c-f40fbda9be3c(CsSampleSln.MyModel)/958873517462047080
Text generation completed successfully
None of generated text units reference context node`

**Comment by wirthma** [comment]
Hey Plasmadog!

Thank you for your interest in our project and reporting the issue!

I just reproduced the same error and it seems that we have made a mistake during the port of the C# base language to the new version of MPS *2020.1*. Sorry for that! We'll fix it and let you know when it's ready (the whole process may take several days).

**Comment by wirthma** [comment]
Hello again!

The issue has been fixed and a new version of the *CsBaseLanguage* plugin has been released. You can update your installed plugin in MPS (it will probably offer you that automatically - if not, go to the plugin manager and update it manually).

I'll close this issue. In case of any further problems, let us know :-)
